#!/usr/bin/env bash
# print bad, good and best schools
index=1
while (($index<=10))
do
	if (($index == 4))
	then
		echo "bad luck"
	elif (($index == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	index=$((index+1))
done
